### ISSUE TITLE
Docker compose command in README.md

### ISSUE THREAD

**Issue by terry-sydaus** [raskitoma/pls_admin#7]
The docker compose command specified in the README.md does not work.

I had to run the following command to get the docker image to build and run.

````bash
sudo docker compose up
````

**Comment by raskitoma** [comment]
Hi, thanks for the note. Thing is I always assume you have a ready docker/docker-compose setup, with an user that has permissions to run it.  That's the reason you needed to "elevate" using `sudo`.

**Comment by terry-sydaus** [comment]
> Hi, thanks for the note. Thing is I always assume you have a ready docker/docker-compose setup, with an user that has permissions to run it. That's the reason you needed to "elevate" using `sudo`.

Thanks for your reply.

Even when I run 

````bash
sudo docker-compose up
````
This command also does not work. The "-" between "docker" and "compose" is causing this, I believe.
I think it might have something to do with the version of docker and docker compose that I am running.
It is not an elevated privilege issue from what I can gather.

**Comment by raskitoma** [comment]
I assume that everyone has already docker and docker compose setup. Thing is, depends on how new/old is your config, depends on how "compose" was installed. There are 2 methods:

- Method 1: as an application (this is the legacy one): This is the one that requires to run as `docker-compose up -d`
- Method 2: as a docker plugin (new one): This is the one that requires to run as `docker compose up -d`

I have a mix of both of them, but mostly #2 is the one I have spread on all my devices.
